POST http://localhost:3000/api/servercom
authorization: kD36bef6cfaASbrbzxK4Gr
Content-Type: application/json

{
  "statusInterval": "19",
  "filename": "helloworld.py",
  "workspace": "hello-py-project",
  "initFileOpened": "2023-05-28T19:20:57.402Z",
  "initWorkspaceOpened": "2023-05-28T19:20:57.402Z",
  "lastPushToServer": "2023-05-28T19:20:57.402Z"
}

###

GET http://localhost:3000/api/status?theme=dark&timefor=file


##

  # .key-name {
  #   fill: {{#333}}; /* Dark gray */
  #   font: 500 12px 'Segoe UI', Ubuntu, Sans-Serif;
  #           <!-- font-weight: bold; -->
  # }

  #   .value {
  #   font: 400 14px 'Segoe UI', Ubuntu, "Helvetica Neue", Sans-Serif; 
  #   fill: #929292;
  #   white-space: nowrap;
  #   overflow: hidden;
  #   width: 0;
  # }

  #   .box {
  #   stroke: #666;
  #   stroke-width: 2px;
  #   rx: 7px;
  #   font-family: Arial, sans-serif;
  #   font-size: 18px;
  # }